[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jeans"
version = "1.0.0"
description = "Jeans modelling for SIDM halos."
authors = [
  { name = "Sean Tulin", email = "stulin@yorku.ca" },
  { name = "Adam Smith-Orlik", email = "asorlik@yorku.ca" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.9,<3.14"
dependencies = [
  "numpy>=2.2,<2.4",
  "scipy>=1.11,<1.17",
  "pandas>=2.2,<2.4",
  "matplotlib>=3.8,<3.11",
  "h5py>=3.12,<3.16",
  "dill>=0.3.8,<0.4.1"
]

[project.urls]
"Source Code" = "https://github.com/dark-physics/jeans.git"

[tool.setuptools]
package-dir = { "" = "src" }
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["jeans*"]

[tool.setuptools.package-data]
jeans = ["data/*.csv"]

[tool.black]
line-length = 120